name: camaras_tv
description: SentriCam, visor de cámaras de DVR/NVR Hikvision para Android TV
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  flutter_secure_storage: ^9.2.2
  wakelock_plus: ^1.2.8
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
